name: basal
description: A scalable, performant and elegant state manager for Flutter
version: 0.1.3
author: Dusan Kovacevic <dusankovacevic95@gmail.com>
homepage: https://gitlab.com/dkovacevic15/basal.git

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=1.19.0 <2.0.0"
