name: basal
description: A new flutter package project.
version: 0.1.0
author: Dusan Kovacevic <dusankovacevic95@gmail.com>
homepage: https://gitlab.com/dkovacevic15/basal.git

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
